### ISSUE TITLE
potentially malicious package name squatter

### ISSUE THREAD

**Issue by ungoldman** [bcomnes/gh-release-test#2]
As I was transferring ownership of this repo, I looked at the package.json and noticed it wasn't set to `private`. I thought I'd give the namespace a peek on `npm`, and lo and behold, someone took the package name **six days ago**.

https://www.npmjs.com/package/gh-release-test

Some red flags:

- the repo address the published version points to doesn't exist: https://github.com/christian1894/gh-release-test
- the npm user only has two packages, gh-release-test and test-fuse-importer-3, both published for the first time within the last ten days
  - https://www.npmjs.com/package/gh-release-test (versions tab)
  - https://www.npmjs.com/package/test-fuse-importer-3 (versions tab)
- the package definitely has nothing to do with gh-release

I've inspected the package contents (avoiding any post-install scripts using the following one-liner: `npm v gh-release-test dist.tarball | xargs curl | tar xzvf -`) and they seem innocuous.

Still, this seems very fishy. Should I contact npm and try to get the package yanked or transferred to us to avoid any potential future danger?

cc @bcomnes @paulcpederson

**Comment by bcomnes** [comment]
Whoa fishy as hell

**Comment by bcomnes** [comment]
Maybe it was an accidental publish when testing gh-release

**Comment by bcomnes** [comment]
Maybe we just ask him directly what's up? Might also just be a coincidence

**Comment by ungoldman** [comment]
We can try!

---

Hey @christian1894, we are trying to figure out if you have taken the `gh-release-test` package name on `npm` on purpose, or by accident, or if something weird is going on. If this was an accident please let us know!

**Comment by paulcpederson** [comment]
oh wow, this is wild!

**Comment by ungoldman** [comment]
Looks like the user no longer exists on Github. I'm going to try to get in touch with npm and see if we can get the package name transferred.

**Comment by bcomnes** [comment]
The plot thickens.

**Comment by ungoldman** [comment]
Tried to send a support request at https://www.npmjs.com/support and got a 404 on submit. 🙃🙃🙃

**Comment by feross** [comment]
Use GitHub support or their HackerOne Bug Bounty program to report.

**Comment by ungoldman** [comment]
Thanks for the tip @feross! Submitted a ticket to Github Support (that one didn't 404 😅), we'll see what happens.

**Comment by ungoldman** [comment]
Hey y'all, just an update on the name dispute saga:

Just short of one year after submitting a support request, I got a response, and they've transferred the gh-release-test package to me.

Happy trails 👋

**Comment by bcomnes** [comment]
Strange. Thanks for looking into that
